language: python
python:
    - 3.6
install:
  - pip install Django==2.0.7
  - npm install
before_script:
  - cp attendancenote/server.py.sample attendancenote/server.py
script:
  - python manage.py migrate
  - python manage.py test
