# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['yearmonth', 'date']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='month',
            new_name='yearmonth',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('yearmonth', 'date')]),
        ),
    ]
