# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180706_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('hour', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance')),
            ],
            options={
                'ordering': ['attendance', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendanceprocess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceprocess',
            unique_together=set([('attendance', 'project')]),
        ),
    ]
