# Generated by Django 2.0.7 on 2018-07-23 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180709_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceprocess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Project'),
        ),
        migrations.AlterField(
            model_name='yearmonth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
