# Generated by Django 2.0.7 on 2018-08-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20180723_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceprocess',
            unique_together=set(),
        ),
    ]
